// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestionaireApi;

#nullable disable

namespace QuestionaireApi.Migrations
{
    [DbContext(typeof(QuestionaireDbContext))]
    [Migration("20250206133447_ChangedCategoryStructureToSupportParentAndMultipleChildren")]
    partial class ChangedCategoryStructureToSupportParentAndMultipleChildren
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuestionaireApi.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("QuestionaireApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "General Knowledge"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Science"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Physics",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Biology",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "History"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Ancient History",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Modern History",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Geography"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "World Geography",
                            ParentCategoryId = 8
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Music"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Sports"
                        });
                });

            modelBuilder.Entity("QuestionaireApi.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuestionaireApi.Models.QuestionCategory", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("QuestionId", "CategoryId");

                    b.ToTable("QuestionCategories");
                });

            modelBuilder.Entity("QuestionaireApi.Models.UserQuestionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId", "QuestionId");

                    b.ToTable("UserQuestionHistory");
                });

            modelBuilder.Entity("QuestionaireApi.Models.Answer", b =>
                {
                    b.HasOne("QuestionaireApi.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuestionaireApi.Models.Category", b =>
                {
                    b.HasOne("QuestionaireApi.Models.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("QuestionaireApi.Models.QuestionCategory", b =>
                {
                    b.HasOne("QuestionaireApi.Models.Category", "Category")
                        .WithMany("QuestionCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionaireApi.Models.Question", "Question")
                        .WithMany("QuestionCategories")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuestionaireApi.Models.UserQuestionHistory", b =>
                {
                    b.HasOne("QuestionaireApi.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuestionaireApi.Models.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("QuestionCategories");
                });

            modelBuilder.Entity("QuestionaireApi.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("QuestionCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
